#!/usr/bin/env node
/**
 * knowflow tags — build tag hub pages from [[tag/<name>]] links.
 *
 * Scans every Markdown page in the wiki for `[[tag/<name>]]` links and
 * (re)generates `tag/<name>.md` hub pages that link back to every page
 * carrying the tag. Hub pages older tags that no longer appear anywhere
 * are removed, so re-running the command is fully idempotent.
 *
 * Environment:
 *   KNOWFLOW_WIKI_DIR — wiki root directory (set by the CLI)
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const WIKI_DIR = process.env.KNOWFLOW_WIKI_DIR;
if (!WIKI_DIR || !existsSync(WIKI_DIR)) {
  console.error('knowflow tags: KNOWFLOW_WIKI_DIR is not set or missing');
  process.exit(1);
}

const TAG_DIR = join(WIKI_DIR, 'tag');
const TAG_LINK = /\[\[tag\/([^\]|]+)(?:\|[^\]]*)?\]\]/g;

function* walkMd(dir) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const path = join(dir, entry.name);
    if (entry.isDirectory()) yield* walkMd(path);
    else if (entry.name.endsWith('.md')) yield path;
  }
}

const tagMap = new Map();
for (const file of walkMd(WIKI_DIR)) {
  const rel = file.slice(WIKI_DIR.length + 1);
  if (rel.startsWith('tag/')) continue;
  const text = readFileSync(file, 'utf8');
  for (const match of text.matchAll(TAG_LINK)) {
    const tag = match[1].trim();
    if (!tag) continue;
    if (!tagMap.has(tag)) tagMap.set(tag, new Set());
    tagMap.get(tag).add(rel.replace(/\.md$/, ''));
  }
}

mkdirSync(TAG_DIR, { recursive: true });

let written = 0;
for (const [tag, pages] of [...tagMap.entries()].sort((a, b) => b[1].size - a[1].size)) {
  const pageList = [...pages].sort();
  const content = [
    `# Tag: ${tag}`,
    '',
    `> Auto-generated by \`knowflow tags\` — index of pages linking to [[tag/${tag}]]. Re-run the command to refresh.`,
    '',
    `## Pages (${pageList.length})`,
    '',
    ...pageList.map(page => `- [[${page}]]`),
    '',
  ].join('\n');
  writeFileSync(join(TAG_DIR, `${tag}.md`), content, 'utf8');
  written += 1;
}

let removed = 0;
for (const entry of existsSync(TAG_DIR) ? readdirSync(TAG_DIR) : []) {
  if (!entry.endsWith('.md')) continue;
  if (!tagMap.has(entry.replace(/\.md$/, ''))) {
    rmSync(join(TAG_DIR, entry));
    removed += 1;
  }
}

console.log(`tags: ${written} hub page(s) under tag/ (${removed} stale removed)`);
